{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Todo API",
    "description": "API for managing todos and todo lists for users."
  },
  "servers": [
    {
      "url": "/api"
    }
  ],
  "paths": {
    "/users": {
      "post": {
        "summary": "Create a new user",
        "requestBody": {
          "description": "User object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestBodyUser"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Retrieve all users",
        "parameters": [
          {
            "$ref": "#/components/parameters/skip"
          },
          {
            "$ref": "#/components/parameters/take"
          },
          {
            "$ref": "#/components/parameters/order"
          }
        ],
        "responses": {
          "200": {
            "description": "List of users",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfUsers"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}": {
      "get": {
        "summary": "Retrieve a specific user by ID",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "User details",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update a specific user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "requestBody": {
          "description": "User object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestBodyUser"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "User details",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/todoLists": {
      "post": {
        "summary": "Create a new todo list for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "requestBody": {
          "description": "Todo list object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestBodyTodoList"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Todo list created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoList"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Retrieve all todo lists for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/skip"
          },
          {
            "$ref": "#/components/parameters/take"
          },
          {
            "$ref": "#/components/parameters/order"
          },
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/includeTodos"
          }
        ],
        "responses": {
          "200": {
            "description": "List of todo lists for the user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfTodoLists"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/todoLists/{todoListId}": {
      "get": {
        "summary": "Retrieve a specific todo list for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoListId"
          }
        ],
        "responses": {
          "200": {
            "description": "Todo list details",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoList"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update a specific todo list for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoListId"
          }
        ],
        "requestBody": {
          "description": "Todo list object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestBodyTodoList"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Todo list updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoList"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete a specific todo list for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoListId"
          },
          {
            "$ref": "#/components/parameters/deleteNestedTodos"
          }
        ],
        "responses": {
          "204": {
            "description": "Todo list deleted successfully"
          }
        }
      }
    },
    "/users/{userId}/todos": {
      "post": {
        "summary": "Create a new todo for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "requestBody": {
          "description": "Todo object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestBodyTodo"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Todo created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todo"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Retrieve all todos for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/skip"
          },
          {
            "$ref": "#/components/parameters/take"
          },
          {
            "$ref": "#/components/parameters/order"
          },
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "List of todos for the user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfTodos"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/todos/{todoId}": {
      "get": {
        "summary": "Retrieve a specific todo for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoId"
          }
        ],
        "responses": {
          "200": {
            "description": "Todo details",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todo"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update a specific todo for a user",
        "requestBody": {
          "description": "Todo object",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestBodyTodo"
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoId"
          }
        ],
        "responses": {
          "200": {
            "description": "Todo updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todo"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete a specific todo for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoId"
          }
        ],
        "responses": {
          "204": {
            "description": "Todo deleted successfully"
          }
        }
      }
    },
    "/users/{userId}/todos/{todoId}/complete": {
      "patch": {
        "summary": "Mark a todo as completed",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoId"
          }
        ],
        "responses": {
          "200": {
            "description": "Todo marked as complete successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todo"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/todos/{todoId}/uncomplete": {
      "patch": {
        "summary": "Mark a todo as uncompleted",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoId"
          }
        ],
        "responses": {
          "200": {
            "description": "Todo marked as uncomplete successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todo"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/todos/{todoId}/toggle": {
      "patch": {
        "summary": "Toggle a todo",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          },
          {
            "$ref": "#/components/parameters/todoId"
          }
        ],
        "responses": {
          "200": {
            "description": "Todo toggled successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todo"
                }
              }
            }
          }
        }
      }
    },
    "/users/{userId}/todos/sync": {
      "post": {
        "summary": "Sync todos with third-party service for a user",
        "parameters": [
          {
            "$ref": "#/components/parameters/userId"
          }
        ],
        "responses": {
          "200": {
            "description": "Todos synced successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfTodos"
                }
              }
            }
          }
        }
      }
    },
    "/webhooks/todoUpdates": {
      "post": {
        "summary": "Webhook endpoint for third-party service updates",
        "responses": {
          "200": {
            "description": "Webhook received successfully"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "description": "User ID"
          },
          "name": {
            "type": "string",
            "description": "User name"
          },
          "email": {
            "type": "string",
            "description": "User email"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "description": "User creation date"
          },
          "updateAt": {
            "type": "string",
            "format": "date-time",
            "description": "User creation date"
          },
          "microsoftUserId": {
            "type": "string",
            "nullable": true,
            "description": "Microsoft user ID associated with the User"
          }
        },
        "example": {
          "id": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
          "createdAt": "2023-08-12T00:18:22.241Z",
          "updatedAt": "2023-08-12T00:18:22.241Z",
          "email": "johndoe@example.com",
          "name": "John Doe",
          "microsoftUserId": "microsoft-user-id"
        }
      },
      "RequestBodyUser": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User name"
          },
          "email": {
            "type": "string",
            "description": "User email"
          }
        },
        "example": {
          "email": "johndoe@example.com",
          "name": "John Doe"
        }
      },
      "ArrayOfUsers": {
        "type": "object",
        "properties": {
          "skip": {
            "type": "integer",
            "description": "Number of items to skip"
          },
          "take": {
            "type": "integer",
            "description": "Number of items to take"
          },
          "total": {
            "type": "integer",
            "description": "Total number of items"
          },
          "results": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/User"
            }
          }
        },
        "example": {
          "skip": 0,
          "take": 10,
          "total": 2,
          "results": [
            {
              "id": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
              "createdAt": "2023-08-12T00:18:22.241Z",
              "updatedAt": "2023-08-12T00:18:22.241Z",
              "email": "johndoe@example.com",
              "name": "John Doe",
              "microsoftUserId": null
            },
            {
              "id": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
              "createdAt": "2023-08-12T00:18:22.241Z",
              "updatedAt": "2023-08-12T00:18:22.241Z",
              "email": "janesmith@example.com",
              "name": "Jane Smith",
              "microsoftUserId": "microsoft-user-id"
            }
          ]
        }
      },
      "TodoList": {
        "type": "object",
        "required": ["id", "title", "userId", "createdAt", "updatedAt"],
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "description": "Todo List ID"
          },
          "title": {
            "type": "string",
            "description": "Todo List title"
          },
          "userId": {
            "type": "string",
            "description": "User ID associated with the Todo List"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "description": "User creation date"
          },
          "updateAt": {
            "type": "string",
            "format": "date-time",
            "description": "User creation date"
          },
          "todos": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Todo"
            }
          }
        },
        "example": {
          "id": "ea6c87fc-a400-4fbc-92bb-be18f488e726",
          "createdAt": "2023-08-12T11:45:56.872Z",
          "updatedAt": "2023-08-12T11:45:56.872Z",
          "title": "adassdas",
          "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f"
        }
      },
      "RequestBodyTodoList": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Todo List title"
          }
        },
        "example": {
          "title": "Work tasks"
        }
      },
      "ArrayOfTodoLists": {
        "type": "object",
        "properties": {
          "skip": {
            "type": "integer",
            "description": "Number of items to skip"
          },
          "take": {
            "type": "integer",
            "description": "Number of items to take"
          },
          "total": {
            "type": "integer",
            "description": "Total number of items"
          },
          "results": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TodoList"
            }
          }
        },
        "example": {
          "skip": 0,
          "take": 10,
          "total": 2,
          "results": [
            {
              "id": "ea6c87fc-a400-4fbc-92bb-be18f488e726",
              "createdAt": "2023-08-12T11:45:56.872Z",
              "updatedAt": "2023-08-12T11:45:56.872Z",
              "title": "adassdas",
              "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f"
            },
            {
              "id": "ea6c87fc-a400-4fbc-92bb-be18f488e726",
              "createdAt": "2023-08-12T11:45:56.872Z",
              "updatedAt": "2023-08-12T11:45:56.872Z",
              "title": "adassdas",
              "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
              "todos": []
            }
          ]
        }
      },
      "Todo": {
        "type": "object",
        "required": [
          "id",
          "title",
          "completed",
          "userId",
          "createdAt",
          "updatedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "description": "Todo ID"
          },
          "title": {
            "type": "string",
            "description": "Todo title"
          },
          "description": {
            "type": "string",
            "nullable": true,
            "description": "Todo description"
          },
          "completed": {
            "type": "boolean",
            "description": "Whether the todo is completed or not"
          },
          "userId": {
            "type": "string",
            "format": "uuid",
            "description": "User ID associated with the Todo"
          },
          "todoListId": {
            "type": "string",
            "nullable": true,
            "format": "uuid",
            "description": "Todo List id associated with the Todo"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "description": "User creation date"
          },
          "updateAt": {
            "type": "string",
            "format": "date-time",
            "description": "User creation date"
          },
          "todoList": {
            "oneOf": [
              {
                "$ref": "#/components/schemas/TodoList"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "example": {
          "id": "b0c79c03-593d-408d-bb3f-40bf1b30d3a8",
          "createdAt": "2023-08-12T13:52:36.346Z",
          "updatedAt": "2023-08-12T13:52:36.346Z",
          "title": "My Todo 1 for list 3",
          "description": "My Todo 1 description for list 3",
          "completed": false,
          "userId": "fc16c877-2581-4fa0-a44c-d1b534a21d62",
          "todoListId": "2b523ac6-3133-4ef4-9c8d-cbee01079191",
          "todoList": {
            "id": "2b523ac6-3133-4ef4-9c8d-cbee01079191",
            "createdAt": "2023-08-12T11:45:56.872Z",
            "updatedAt": "2023-08-12T11:45:56.872Z",
            "title": "adassdas",
            "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f"
          }
        }
      },
      "RequestBodyTodo": {
        "type": "object",
        "required": ["title"],
        "properties": {
          "title": {
            "type": "string",
            "description": "Todo title"
          },
          "description": {
            "type": "string",
            "nullable": true,
            "description": "Todo description"
          },
          "todoListId": {
            "type": "string",
            "nullable": true,
            "format": "uuid",
            "description": "Todo List id associated with the Todo"
          }
        },
        "example": {
          "title": "My Todo 1 for list 3",
          "description": "My Todo 1 description for list 3",
          "todoListId": "2b523ac6-3133-4ef4-9c8d-cbee01079191"
        }
      },
      "ArrayOfTodos": {
        "type": "object",
        "properties": {
          "skip": {
            "type": "integer",
            "description": "Number of items to skip"
          },
          "take": {
            "type": "integer",
            "description": "Number of items to take"
          },
          "total": {
            "type": "integer",
            "description": "Total number of items"
          },
          "results": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Todo"
            }
          }
        },
        "example": {
          "skip": 0,
          "take": 10,
          "total": 2,
          "results": [
            {
              "id": "4c2e0777-c652-4dac-8473-9c6f873f8137",
              "createdAt": "2023-08-12T23:56:01.728Z",
              "updatedAt": "2023-08-12T23:56:01.728Z",
              "title": "My TODO TO TEST ",
              "description": "THIS TODO IS BEING TESTED",
              "completed": false,
              "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
              "todoListId": null,
              "todoList": null
            },
            {
              "id": "f91b1c6d-f5a8-43ac-be45-b5145cc81ecd",
              "createdAt": "2023-08-12T23:57:13.849Z",
              "updatedAt": "2023-08-12T23:57:13.849Z",
              "title": "My TODO TO TEST ANOTHER",
              "description": "THIS TODO IS BEING TESTED ANOTHER",
              "completed": false,
              "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
              "todoListId": "ea6c87fc-a400-4fbc-92bb-be18f488e726",
              "todoList": {
                "id": "ea6c87fc-a400-4fbc-92bb-be18f488e726",
                "createdAt": "2023-08-12T11:45:56.872Z",
                "updatedAt": "2023-08-12T20:15:25.718Z",
                "title": "Work tasks",
                "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f"
              }
            },
            {
              "id": "9ca31d1d-e9c5-4ae3-8379-c8d9d48311ab",
              "createdAt": "2023-08-13T12:49:54.789Z",
              "updatedAt": "2023-08-13T12:49:54.789Z",
              "title": "My Todo 22 no list",
              "description": "My Todo 22",
              "completed": false,
              "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
              "todoListId": null,
              "todoList": null
            },
            {
              "id": "fbb32d78-eab6-4cec-a999-82e7303203ff",
              "createdAt": "2023-08-13T12:50:41.501Z",
              "updatedAt": "2023-08-13T12:50:41.501Z",
              "title": "My Todo 33 for a list",
              "description": "My Todo 33",
              "completed": false,
              "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
              "todoListId": "ea6c87fc-a400-4fbc-92bb-be18f488e726",
              "todoList": {
                "id": "ea6c87fc-a400-4fbc-92bb-be18f488e726",
                "createdAt": "2023-08-12T11:45:56.872Z",
                "updatedAt": "2023-08-12T20:15:25.718Z",
                "title": "Work tasks",
                "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f"
              }
            },
            {
              "id": "1f31959d-ad6b-4d20-923f-65a2d285fb83",
              "createdAt": "2023-08-13T12:51:09.208Z",
              "updatedAt": "2023-08-13T12:51:09.208Z",
              "title": "My Todo 44 for another list",
              "description": "My Todo 44",
              "completed": false,
              "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f",
              "todoListId": "26f3cf66-74dc-43ff-8a27-715ca82a4dba",
              "todoList": {
                "id": "26f3cf66-74dc-43ff-8a27-715ca82a4dba",
                "createdAt": "2023-08-12T12:21:49.033Z",
                "updatedAt": "2023-08-12T12:21:49.033Z",
                "title": "adasdasasdsdas",
                "userId": "05aef8f6-8a54-44ce-ab7d-87e67ea9ad2f"
              }
            }
          ]
        }
      }
    },
    "parameters": {
      "skip": {
        "name": "skip",
        "in": "query",
        "required": false,
        "description": "Number of items to skip",
        "schema": {
          "type": "integer",
          "default": 0
        }
      },
      "take": {
        "name": "take",
        "in": "query",
        "required": false,
        "description": "Number of items to take",
        "schema": {
          "type": "integer",
          "default": 10
        }
      },
      "order": {
        "name": "order",
        "in": "query",
        "required": false,
        "description": "Order of items",
        "schema": {
          "type": "string",
          "default": "asc"
        }
      },
      "userId": {
        "name": "userId",
        "in": "path",
        "required": true,
        "description": "Unique identifier of the user",
        "schema": {
          "type": "string"
        }
      },
      "todoListId": {
        "name": "todoListId",
        "in": "path",
        "required": true,
        "description": "Unique identifier of the todo list",
        "schema": {
          "type": "string"
        }
      },
      "todoId": {
        "name": "todoId",
        "in": "path",
        "required": true,
        "description": "Unique identifier of the todo",
        "schema": {
          "type": "string"
        }
      },
      "includeTodos": {
        "name": "includeTodos",
        "in": "query",
        "required": false,
        "description": "Include todos in the response",
        "schema": {
          "type": "boolean"
        }
      },
      "deleteNestedTodos": {
        "name": "deleteNestedTodos",
        "in": "query",
        "required": false,
        "description": "Delete nested todos",
        "schema": {
          "type": "boolean"
        }
      }
    }
  }
}
